  // lib/email-templates.ts

  const baseStyles = {
    bg: '#fff7e9',
    text: '#0e2a36',
    card: '#ffffff',
    border: '#e5ddd0',
    primary: '#0e2a36',
    accent: '#b68c5a',
  }

  type Locale = 'es' | 'en' | 'fr'

  // Traducciones para los emails
  const emailTexts = {
    es: {
      services: 'SERVICIOS',
      tour: 'TOUR',
      transfer: 'TRASLADO',
      event: 'EVENTO',
      service: 'SERVICIO',
      thanksTitle: '¡Gracias por tu pago!',
      thanksIntro: (name?: string) => `Hola${name ? ' ' + name : ''}, gracias por confiar en nosotros.`,
      thanksMessage: '¡Gracias por tu pago y tu confianza!',
      paymentReceived: 'Hemos recibido tu pago y tus reservas han quedado confirmadas.',
      contractedServices: 'Servicios contratados',
      totalServices: 'Total de servicios',
      teamSignature: 'Equipo de Redeservi Europa',
      date: 'Fecha',
      time: 'Hora',
      pickup: 'Recogida',
      destination: 'Destino',
      passengers: 'Pasajeros',
      children: 'Niños',
      childrenAges: 'Edades de los niños',
      total: 'Total',
      paid: 'Pagado',
      flight: 'Vuelo',
      luggage23kg: 'Maletas 23kg',
      luggage10kg: 'Maletas 10kg',
      newReservation: 'Nueva reserva confirmada',
      newReservations: 'Nuevas reservas confirmadas',
      summaryTitle: 'Resumen de reservas',
      contact: 'Contacto',
      name: 'Nombre',
      email: 'Email',
      phone: 'Teléfono',
      howKnowUs: '¿Cómo nos conoció?',
      autoGenerated: 'Generado automáticamente',
      paymentConfirmed: 'Se ha confirmado un pago y los servicios asociados han quedado registrados.',
      serviceNumber: (n: number) => `Servicio ${n}`,
    },
    en: {
      services: 'SERVICES',
      tour: 'TOUR',
      transfer: 'TRANSFER',
      event: 'EVENT',
      service: 'SERVICE',
      thanksTitle: 'Thank you for your payment!',
      thanksIntro: (name?: string) => `Hello${name ? ' ' + name : ''}, thank you for trusting us.`,
      thanksMessage: 'Thank you for your payment and your trust!',
      paymentReceived: 'We have received your payment and your reservations have been confirmed.',
      contractedServices: 'Contracted services',
      totalServices: 'Total services',
      teamSignature: 'Redeservi Europa Team',
      date: 'Date',
      time: 'Time',
      pickup: 'Pickup',
      destination: 'Destination',
      passengers: 'Passengers',
      children: 'Children',
      childrenAges: 'Children ages',
      total: 'Total',
      paid: 'Paid',
      flight: 'Flight',
      luggage23kg: '23kg luggage',
      luggage10kg: '10kg luggage',
      newReservation: 'New reservation confirmed',
      newReservations: 'New reservations confirmed',
      summaryTitle: 'Reservation summary',
      contact: 'Contact',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      howKnowUs: 'How did you hear about us?',
      autoGenerated: 'Automatically generated',
      paymentConfirmed: 'A payment has been confirmed and the associated services have been registered.',
      serviceNumber: (n: number) => `Service ${n}`,
    },
    fr: {
      services: 'SERVICES',
      tour: 'TOUR',
      transfer: 'TRANSFERT',
      event: 'ÉVÉNEMENT',
      service: 'SERVICE',
      thanksTitle: 'Merci pour votre paiement !',
      thanksIntro: (name?: string) => `Bonjour${name ? ' ' + name : ''}, merci de votre confiance.`,
      thanksMessage: 'Merci pour votre paiement et votre confiance !',
      paymentReceived: 'Nous avons reçu votre paiement et vos réservations ont été confirmées.',
      contractedServices: 'Services contractés',
      totalServices: 'Total des services',
      teamSignature: 'Équipe Redeservi Europa',
      date: 'Date',
      time: 'Heure',
      pickup: 'Prise en charge',
      destination: 'Destination',
      passengers: 'Passagers',
      children: 'Enfants',
      childrenAges: 'Âges des enfants',
      total: 'Total',
      paid: 'Payé',
      flight: 'Vol',
      luggage23kg: 'Bagages 23kg',
      luggage10kg: 'Bagages 10kg',
      newReservation: 'Nouvelle réservation confirmée',
      newReservations: 'Nouvelles réservations confirmées',
      summaryTitle: 'Résumé des réservations',
      contact: 'Contact',
      name: 'Nom',
      email: 'Email',
      phone: 'Téléphone',
      howKnowUs: 'Comment nous avez-vous connu ?',
      autoGenerated: 'Généré automatiquement',
      paymentConfirmed: 'Un paiement a été confirmé et les services associés ont été enregistrés.',
      serviceNumber: (n: number) => `Service ${n}`,
    },
  }

  function overallTag(services?: Array<{ type?: string }>, locale: Locale = 'es') {
    const list = services || []
    const hasTour = list.some(s => (s?.type || '').toLowerCase() === 'tour')
    const hasTras = list.some(s => (s?.type || '').toLowerCase() === 'traslado')
    const hasEvt  = list.some(s => (s?.type || '').toLowerCase() === 'evento')
    const kinds = [hasTour, hasTras, hasEvt].filter(Boolean).length
    const texts = emailTexts[locale]
    if (kinds > 1) return texts.services
    if (hasTour) return texts.tour
    if (hasTras) return texts.transfer
    if (hasEvt)  return texts.event
    return texts.services
  }

  function absLogoUrl(): string {
    const site = (process.env.NEXT_PUBLIC_SITE_URL || '').replace(/\/+$/, '')
    const envLogo = process.env.EMAIL_LOGO_URL && process.env.EMAIL_LOGO_URL.startsWith('http')
      ? process.env.EMAIL_LOGO_URL
      : null
    if (envLogo) return envLogo
    if (site) return `${site}/images/logo.png`
    // Fallback a una imagen “dummy” pública y absoluta para evitar roturas
    return 'https://via.placeholder.com/200x60?text=Redeservi+Europa'
  }

  export function renderBrandEmail({ title, intro, contentHtml, footerNote }: {
    title: string
    intro?: string
    contentHtml: string
    footerNote?: string
  }) {
    const { bg, text, card, border, primary, accent } = baseStyles
    const logoUrl = absLogoUrl()
    return `
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>${escapeHtml(title)}</title>
        <style>
          body { margin:0; padding:0; background:${bg}; color:${text}; font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; }
          .container { max-width:640px; margin:0 auto; padding:24px; }
          .brand { text-align:center; margin: 8px 0 16px; }
          .brand img { display:inline-block; max-height:64px; height:auto; width:auto; }
          .card { background:${card}; border:1px solid ${border}; border-radius:12px; padding:24px; box-shadow:0 1px 3px rgba(0,0,0,0.05); }
          .title { color:${primary}; font-size:22px; margin:0 0 8px; letter-spacing: 0.2px; }
          .subtitle { color:#3b5763; margin:0 0 16px; }
          .button { display:inline-block; background:${accent}; color:#fff; text-decoration:none; padding:10px 16px; border-radius:8px; font-weight:600; }
          .muted { color:#5f7b87; font-size:12px; }
          .hr { border: none; border-top: 1px solid ${border}; margin: 16px 0; }
          .list { padding-left: 20px; }
          .list li { margin-bottom: 6px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="brand">
            <img src="${logoUrl}" alt="Redeservi Europa" width="200" height="60"/>
          </div>
          <div class="card">
            <h1 class="title">${escapeHtml(title)}</h1>
            ${intro ? `<p class="subtitle">${escapeHtml(intro)}</p>` : ''}
            <div>${contentHtml}</div>
            ${footerNote ? `<hr class="hr"/><p class="muted">${escapeHtml(footerNote)}</p>` : ''}
          </div>
        </div>
      </body>
    </html>`
  }

  function escapeHtml(str: string) {
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;')
  }

  export function paymentStatusEs(status?: string): string {
    switch ((status || '').toLowerCase()) {
      case 'paid': return 'Pagado'
      case 'pending': return 'Pendiente'
      case 'open': return 'Abierto'
      case 'failed': return 'Fallido'
      case 'canceled': return 'Cancelado'
      case 'expired': return 'Expirado'
      case 'authorized': return 'Autorizado'
      default: return status || 'Desconocido'
    }
  }

  export function paymentMethodLabel(method?: string | null): string {
    switch ((method || '').toLowerCase()) {
      case 'creditcard': return 'Tarjeta'
      case 'paypal': return 'PayPal'
      case 'bancontact': return 'Bancontact'
      case 'ideal': return 'iDEAL'
      case 'banktransfer': return 'Transferencia bancaria'
      default: return method || '—'
    }
  }

  /** ========= Depósito por tipo =========
   *  - tour -> 20%
   *  - traslado -> 10%
   *  - evento -> 20% (por defecto)
   *  - payFullNow -> 100%
   */
  function depositPercentFor(type?: string, payFullNow?: boolean, explicit?: number | null): number {
    if (payFullNow) return 100
    if (typeof explicit === 'number' && explicit >= 0 && explicit <= 100) return explicit
    const t = (type || '').toLowerCase()
    if (t === 'traslado') return 10
    if (t === 'tour') return 20
    return 20 // evento/otros
  }

  function round1(n: number) { return Math.round(n * 10) / 10 }

  function tagServicio(type?: string, locale: Locale = 'es') {
    const t = (type || '').toLowerCase()
    const texts = emailTexts[locale]
    if (t === 'traslado') return texts.transfer
    if (t === 'tour') return texts.tour
    if (t === 'evento') return texts.event
    return texts.service
  }

  /** ============ Email CLIENTE (múltiples) ============ */
  export function renderClientThanksEmailMulti(params: {
    mollieId: string
    amount?: number | string
    currency?: string
    contact?: { name?: string; email?: string; phone?: string; referralSource?: string }
    services?: Array<{
      type?: string; title?: string; date?: string; time?: string;
      totalPrice?: number; pickupAddress?: string; dropoffAddress?: string;
      passengers?: number; ninos?: number; ninosMenores9?: string; payFullNow?: boolean; depositPercent?: number | null
    }>
    locale?: Locale
  }) {
    const locale = params.locale || 'es'
    const texts = emailTexts[locale]
    const services = params.services || []
    const itemsHtml = services.map(s => {
      const total = Number(s.totalPrice || 0)
      const percent = depositPercentFor(s.type, s.payFullNow, s.depositPercent ?? null)
      const paidNow = round1(total * (percent / 100))
      const tag = tagServicio(s.type, locale)

      return `
        <li>
          <b>[${tag}]</b> ${escapeHtml(s.title || 'Reserva')}<br/>
          <b>${texts.date}:</b> ${escapeHtml(s.date || '\u2014')}<br/>
          <b>${texts.time}:</b> ${escapeHtml(s.time || '\u2014')}<br/>
          <b>${texts.pickup}:</b> ${escapeHtml(s.pickupAddress || '\u2014')}<br/>
          <b>${texts.destination}:</b> ${escapeHtml(s.dropoffAddress || '\u2014')}<br/>
          <b>${texts.passengers}:</b> ${typeof s.passengers === 'number' ? s.passengers : '\u2014'}<br/>
          ${typeof s.ninos === 'number' && s.ninos > 0 ? `<b>${texts.children}:</b> ${s.ninos}<br/>` : ''}
          ${s.ninosMenores9 ? `<b>${texts.childrenAges}:</b> ${escapeHtml(s.ninosMenores9)}<br/>` : ''}
          <b>${texts.total}:</b> ${total.toFixed(2)} €<br/>
          <b>${percent === 100 ? texts.paid : `${texts.paid} (${percent}%)`}:</b> ${paidNow.toFixed(1)} €
        </li>
      `
    }).join('')

    const totalSum = services.reduce((acc, s) => acc + (s.totalPrice || 0), 0)
    const contentHtml = `
      <p>${texts.thanksMessage}</p>
      <p>${texts.paymentReceived}</p>
      <h3>${texts.contractedServices}</h3>
      <ul class="list">
        ${itemsHtml}
      </ul>
      <p><b>${texts.totalServices}:</b> ${totalSum.toFixed(2)} ${params.currency || 'EUR'}</p>
    `
    
    return renderBrandEmail({
      title: texts.thanksTitle,
      intro: texts.thanksIntro(params.contact?.name),
      contentHtml,
      footerNote: texts.teamSignature
    })
  }

  /** ============ Email ADMIN (múltiples) ============ */
  export function renderAdminNewServicesEmailMulti(params: {
    mollieId: string
    amount?: number | string
    currency?: string
    method?: string | null
    requestedMethod?: string | null
    contact?: { name?: string; email?: string; phone?: string; referralSource?: string }
    services?: Array<{
      type?: string; title?: string; date?: string; time?: string;
      totalPrice?: number; pickupAddress?: string; dropoffAddress?: string;
      flightNumber?: string;
      luggage23kg?: number; luggage10kg?: number;
      passengers?: number; ninos?: number; ninosMenores9?: string; payFullNow?: boolean; depositPercent?: number | null
    }>
    locale?: Locale
  }) {
    const locale = params.locale || 'es'
    const texts = emailTexts[locale]
    const services = params.services || []
    
    // Determinar el título según la cantidad de servicios
    const isMultiple = services.length > 1
    const title = isMultiple ? texts.summaryTitle : tagServicio(services[0]?.type, locale)

    const itemsHtml = services.map((s, idx) => {
      const total = Number(s.totalPrice || 0)
      const percent = depositPercentFor(s.type, s.payFullNow, s.depositPercent ?? null)
      const paidNow = round1(total * (percent / 100))
      const tag = tagServicio(s.type, locale)

      // ✈️ Linea de vuelo solo si hay número de vuelo
        const flightLine = s.flightNumber 
          ? `<b>${texts.flight}:</b> ${escapeHtml(s.flightNumber)}`
          : ''

      // 🧳 Linea de maletas si hay alguna
      const luggageLine =
        (Number(s.luggage23kg || 0) > 0 || Number(s.luggage10kg || 0) > 0)
          ? `<b>${texts.luggage23kg}:</b> ${Number(s.luggage23kg || 0)}<br/><b>${texts.luggage10kg}:</b> ${Number(s.luggage10kg || 0)}`
          : ''

      return `
        <li>
          ${isMultiple ? `<b>${texts.serviceNumber(idx + 1)}:</b><br/>` : ''}<b>[${tag}]</b> ${escapeHtml(s.title || 'Reserva')}<br/>
          <b>${texts.date}:</b> ${escapeHtml(s.date || '\u2014')}<br/>
          <b>${texts.time}:</b> ${escapeHtml(s.time || '\u2014')}<br/>
          <b>${texts.pickup}:</b> ${escapeHtml(s.pickupAddress || '\u2014')}<br/>
          <b>${texts.destination}:</b> ${escapeHtml(s.dropoffAddress || '\u2014')}<br/>
          ${flightLine ? `${flightLine}<br/>` : ''}
          ${luggageLine ? `${luggageLine}<br/>` : ''}
          <b>${texts.passengers}:</b> ${typeof s.passengers === 'number' ? s.passengers : '\u2014'}<br/>
          ${typeof s.ninos === 'number' && s.ninos > 0 ? `<b>${texts.children}:</b> ${s.ninos}<br/>` : ''}
          ${s.ninosMenores9 ? `<b>${texts.childrenAges}:</b> ${escapeHtml(s.ninosMenores9)}<br/>` : ''}
          <b>${texts.total}:</b> ${total.toFixed(2)} €<br/>
          <b>${percent === 100 ? texts.paid : `${texts.paid} (${percent}%)`}:</b> ${paidNow.toFixed(1)} €
        </li>
      `
    }).join('')

    const totalSum = services.reduce((acc, s) => acc + (s.totalPrice || 0), 0)

    // 👇 "¿Cómo nos conoció?" ahora sí llega por contact.referralSource (o en su defecto podría venir en service.referralSource)
    const contactBlock = params.contact ? `
      <h3>${texts.contact}</h3>
      <ul class="list">
        <li><b>${texts.name}:</b> ${escapeHtml(params.contact.name || '—')}</li>
        <li><b>${texts.email}:</b> ${escapeHtml(params.contact.email || '—')}</li>
        <li><b>${texts.phone}:</b> ${escapeHtml(params.contact.phone || '—')}</li>
        <li><b>${texts.howKnowUs}</b> ${escapeHtml(params.contact.referralSource || '—')}</li>
      </ul>
    ` : ''

    const contentHtml = `
      <p><b>${isMultiple ? texts.newReservations : texts.newReservation}</b></p>
      <ul class="list">
        ${itemsHtml}
      </ul>
      <p><b>${texts.totalServices}:</b> ${totalSum.toFixed(2)} ${params.currency || 'EUR'}</p>
      ${contactBlock}
    `
    return renderBrandEmail({
      title: `[${title}] ${isMultiple ? texts.newReservations : texts.newReservation}`,
      intro: texts.paymentConfirmed,
      contentHtml,
      footerNote: texts.autoGenerated
    })
  }
