export interface TourInfo {
  title: string
  description: string
  basePrice?: number
  basePriceDay?: number
  basePriceNight?: number
  duration: string
  distance: string
  image: string
  gallery?: string[]
  features: string[]
  included: string[]
  pricing?: Record<number, number>
  pricingP4?: { threeH: number; twoH: number; eiffelArco: number }
  pricingP5?: { threeH: number; twoH: number; eiffelArco: number }
  amenities?: string[]
  pricingOptions?: Array<{ label: string; hours?: number; price: number; description?: string }>
}

export const tourData: Record<string, TourInfo> = {
  "cdg-paris": {
    title: "Traslado CDG ↔ París",
    description:
      "Servicio premium de traslado desde/hacia el aeropuerto Charles de Gaulle al centro de París. Nuestros conductores profesionales te esperarán en la terminal con un cartel con tu nombre.",
    basePrice: 65,
    duration: "45-60 min",
    distance: "35 km",
    image: "/luxury-car-at-charles-de-gaulle-airport-paris.jpg",
    gallery: [
      "/luxury-car-at-charles-de-gaulle-airport-paris.jpg",
      "/vehicles/stepway-paris-2.jpg",
      "/vehicles/stepway-paris-3.jpg",
      "/vehicles/stepway-paris-4.jpg",
      "/vehicles/stepway-paris-5.jpg",
    ],
    features: [
      "Seguimiento de vuelo en tiempo real",
      "Conductor profesional uniformado",
      "Vehículo Mercedes-Benz o similar",
      "WiFi gratuito a bordo",
      "Agua embotellada de cortesía",
      "Asistencia con equipaje",
      "Pago con tarjeta o efectivo",
      "Cancelación gratuita hasta 24h antes",
    ],
    included: [
      "Recogida en terminal",
      "Espera gratuita 60 min",
      "Peajes incluidos",
      "Seguro completo",
      "Conductor de habla hispana o inglesa o francés",
      "Vehículo amplio",
    ],
    amenities: [
      "WiFi a bordo",
      "Agua de cortesía",
      "Cargadores USB",
      "Climatización bizona",
      "Asientos confort",
      "Seguimiento de vuelo",
    ],
    pricingOptions: [
      { label: "Servicio estándar", price: 65, description: "Hasta 4 pasajeros" },
      { label: "Minivan familiar", price: 85, description: "+ de 4 hasta 5 pax" },
      { label: "Grupo 6-7 pax", price: 103 },
      { label: "Grupo 8 pax", price: 113 },
      { label: "Servicio VIP Welcome", price: 125, description: "Incluye meet & greet prioritario y asistencia extra equipaje" },
      { label: "Vehículo de Lujo Executive", price: 155, description: "Sedán premium / Business Class" },
    ],
    pricing: {
      1: 65,
      2: 65,
      3: 65,
      4: 65,
      5: 85,
      6: 103,
      7: 109,
      8: 113,
    },
  },
  "orly-paris": {
    title: "Traslado Orly ↔ París",
    description:
      "Conexión directa y cómoda entre el aeropuerto de Orly y el centro de París. Servicio puerta a puerta con la máxima comodidad.",
    basePrice: 60,
    duration: "35-45 min",
    distance: "25 km",
    image: "/elegant-transport-service-orly-airport-paris.jpg",
    gallery: [
      "/elegant-transport-service-orly-airport-paris.jpg",
      "/vehicles/stepway-paris-1.jpg",
      "/vehicles/stepway-paris-6.jpg",
      "/elegant-paris-skyline-with-eiffel-tower-and-luxury.jpg",
    ],
    features: [
      "Servicio puerta a puerta",
      "Vehículos de lujo",
      "Conductores bilingües",
      "Sistema de climatización",
      "Música ambiente",
      "Cargadores USB",
      "Servicio 24/7",
      "Confirmación inmediata",
    ],
    included: [
      "Recogida en terminal",
      "Espera gratuita 45 min",
      "Peajes incluidos",
      "Limpieza del vehículo",
      "Conductor de habla hispana o inglesa o francés",
      "Vehículo cómodo",
    ],
    amenities: [
      "WiFi a bordo",
      "Agua de cortesía",
      "Asientos confort",
      "Climatización bizona",
      "Cargadores USB",
      "Confirmación inmediata",
    ],
    pricingOptions: [
      { label: "Servicio estándar", price: 60 },
      { label: "Minivan familiar", price: 80 },
      { label: "Grupo 6 pax", price: 95 },
      { label: "Grupo 7 pax", price: 104 },
      { label: "Grupo 8 pax", price: 108 },
      { label: "Vehículo Premium", price: 135, description: "Sedán ejecutivo (bajo disponibilidad)" },
      { label: "Servicio Express Prioritario", price: 125, description: "Salida inmediata + coordinación avanzada" },
    ],
    pricing: {
      1: 60,
      2: 60,
      3: 60,
      4: 60,
      5: 80,
      6: 95,
      7: 104,
      8: 108,
    },
  },
  "paris-disneyland": {
    title: "París ↔ Disneyland",
    description:
      "Traslado mágico hacia el reino de la fantasía. Perfecto para familias, con espacio extra para equipaje y entretenimiento para los más pequeños.",
    basePrice: 70,
    duration: "45-60 min",
    distance: "40 km",
    image: "/family-transport-to-disneyland-paris-castle.jpg",
    gallery: [
      "/family-transport-to-disneyland-paris-castle.jpg",
      "/elegant-woman-smiling.png",
      "/vehicles/stepway-paris-2.jpg",
    ],
    features: [
      "Perfecto para familias",
      "Entretenimiento para niños",
      "Asientos elevadores disponibles",
      "Espacio extra para equipaje",
      "Paradas técnicas si necesario",
      "Información sobre el parque",
      "Fotos de recuerdo",
      "Horarios flexibles",
    ],
    included: [
      "Recogida en hotel",
      "Entrada directa al parque",
      "Mapa del parque",
      "Recomendaciones VIP",
      "Conductor de habla hispana o inglesa o francés",
      "Vehículo amplio",
    ],
    amenities: [
      "WiFi a bordo",
      "Agua de cortesía",
      "Asientos para niños bajo solicitud",
      "Climatización bizona",
      "Espacio extra equipaje",
      "Conductor bilingüe",
    ],
    pricingOptions: [
      { label: "Hasta 4 pasajeros", price: 70 },
      { label: "5 pasajeros", price: 90 },
      { label: "6 pasajeros", price: 106 },
      { label: "7 pasajeros", price: 118 },
      { label: "8 pasajeros", price: 134 },
      { label: "VIP Familiar + Fotos", price: 165, description: "Incluye mini sesión fotográfica y snacks" },
      { label: "XL Equipaje Extra", price: 150, description: "Vehículo con espacio adicional" },
    ],
    pricing: {
      1: 70,
      2: 70,
      3: 70,
      4: 70,
      5: 90,
      6: 106,
      7: 118,
      8: 134,
    },
  },
  "tour-paris": {
    title: "Tour por París",
    description:
      "Descubre la Ciudad de la Luz con nuestro tour personalizado. Recorre los monumentos más emblemáticos de París con un conductor profesional que te contará la historia de cada lugar.",
    basePriceDay: 55,
    basePriceNight: 65,
    duration: "Mínimo 2 horas",
    distance: "Personalizable",
    image: "/vehicles/stepway-paris-4.jpg",
    gallery: [
      "/vehicles/stepway-paris-1.jpg",
      "/vehicles/stepway-paris-3.jpg",
      "/vehicles/stepway-paris-4.jpg",
      "/vehicles/stepway-paris-5.jpg",
      "/vehicles/stepway-paris-6.jpg",
      "/elegant-paris-skyline-with-eiffel-tower-and-luxury.jpg",
    ],
    features: [
      "Tour personalizable",
      "Paradas en monumentos principales",
      "Conductor guía profesional",
      "Vehículo cómodo y amplio",
      "Fotos en lugares emblemáticos",
      "Información histórica",
      "Flexibilidad de horarios",
      "Rutas adaptadas a tus intereses",
    ],
    included: [
      "Conductor de habla hispana o inglesa o francés",
      "Vehículo cómodo",
      "Combustible incluido",
      "Estacionamiento incluido",
    ],
    amenities: [
      "WiFi a bordo",
      "Agua de cortesía",
      "Cargadores USB",
      "Vehículo premium",
      "Climatización bizona",
      "Fotos en paradas",
    ],
    pricingOptions: [
      { label: "Tour 2h diurno", hours: 2, price: 110, description: "Ejemplo estimado (base 55€/h)" },
      { label: "Tour 3h diurno", hours: 3, price: 165 },
      { label: "Tour 2h nocturno", hours: 2, price: 130, description: "Base 65€/h" },
      { label: "Tour 3h nocturno", hours: 3, price: 195 },
      { label: "Tour 4h diurno", hours: 4, price: 220 },
      { label: "Tour 4h nocturno", hours: 4, price: 260 },
      { label: "Tour Fotográfico Premium", hours: 3, price: 240, description: "Incluye paradas extendidas y asistencia para fotos" },
    ],
  },
  "paris-dl-dl": {
    title: "Disneyland ➡ Paris Tour ➡ Disneyland",
    description:
      "Disfruta un recorrido por París saliendo desde Disneyland y regresando al mismo punto. Ideal para conocer lo imprescindible en un solo trayecto con paradas para fotos.",
    basePrice: 200,
    duration: "2h · 3h o circuito Eiffel + Arco",
    distance: "Circuito en París",
    image: "/vehicles/stepway-paris-1.jpg",
    gallery: [
      "/vehicles/stepway-paris-1.jpg",
      "/vehicles/stepway-paris-2.jpg",
      "/vehicles/stepway-paris-3.jpg",
      "/vehicles/stepway-paris-4.jpg",
      "/vehicles/stepway-paris-5.jpg",
      "/vehicles/stepway-paris-6.jpg",
    ],
    features: [
      "Salida y regreso a Disneyland",
      "Paradas en puntos icónicos",
      "Conductor guía profesional",
      "Vehículo cómodo y amplio",
      "Itinerario optimizado según tráfico",
      "Flexibilidad de horarios",
      "Fotos en lugares emblemáticos",
      "Servicio privado",
    ],
    included: [
      "Conductor de habla hispana o inglesa o francés",
      "Vehículo cómodo",
      "Combustible y peajes",
      "Estacionamiento incluido",
    ],
    amenities: [
      "WiFi a bordo",
      "Agua de cortesía",
      "Cargadores USB",
      "Vehículo amplio",
      "A/C bizona",
      "Guía básico",
    ],
    pricingOptions: [
      { label: "Hasta 4 pax - 3h", hours: 3, price: 300 },
      { label: "Hasta 4 pax - 2h", hours: 2, price: 245 },
      { label: "Hasta 4 pax - Eiffel + Arco", price: 200 },
      { label: "Hasta 5 pax - 3h", hours: 3, price: 340 },
      { label: "Hasta 5 pax - 2h", hours: 2, price: 315 },
      { label: "Hasta 5 pax - Eiffel + Arco", price: 245 },
      { label: "Hasta 4 pax - 3h Sunset", hours: 3, price: 330, description: "Horario atardecer (luz dorada)" },
      { label: "Hasta 5 pax - 3h Sunset", hours: 3, price: 370, description: "Horario atardecer especial" },
    ],
    pricingP4: { threeH: 300, twoH: 245, eiffelArco: 200 },
    pricingP5: { threeH: 340, twoH: 315, eiffelArco: 245 },
  },
  "orly-disneyland": {
    title: "Orly ↔ Disneyland",
    description:
      "Traslado directo entre el Aeropuerto de Orly y Disneyland París. Ideal para familias que desean optimizar tiempos el día de llegada o salida.",
    basePrice: 78,
    duration: "40-55 min",
    distance: "45 km",
    image: "/vehicles/stepway-paris-2.jpg",
    gallery: [
      "/vehicles/stepway-paris-2.jpg",
      "/vehicles/stepway-paris-6.jpg",
      "/family-transport-to-disneyland-paris-castle.jpg",
      "/elegant-paris-skyline-with-eiffel-tower-and-luxury.jpg",
    ],
    features: [
      "Recepción en terminal",
      "Monitorización de vuelo",
      "Vehículo amplio y climatizado",
      "Conductores bilingües",
      "Sin cargos ocultos",
      "Atención familiar",
      "Servicio 24/7",
      "Reserva flexible",
    ],
    included: [
      "Seguimiento de vuelo",
      "Peajes incluidos",
      "Conductor de habla hispana o inglesa o francés",
      "Agua de cortesía",
      "Seguro y licencias",
      "Ayuda con equipaje",
    ],
    amenities: [
      "WiFi a bordo",
      "Cargadores USB",
      "Agua de cortesía",
      "Asientos confort",
      "Climatización bizona",
      "Sillas niños bajo solicitud",
    ],
    pricingOptions: [
      { label: "Hasta 4 pasajeros", price: 78 },
      { label: "5 pasajeros", price: 95 },
      { label: "6 pasajeros", price: 112 },
      { label: "7 pasajeros", price: 124 },
      { label: "8 pasajeros", price: 138 },
      { label: "Familiar XL + equipaje", price: 155, description: "Mayor capacidad de maletas" },
    ],
    pricing: {
      1: 78,
      2: 78,
      3: 78,
      4: 78,
      5: 95,
      6: 112,
      7: 124,
      8: 138,
    },
  },
  "cdg-disneyland": {
    title: "CDG ↔ Disneyland",
    description:
      "Conecta Charles de Gaulle con la magia de Disneyland sin complicaciones. Puntualidad, confort y atención en tu idioma.",
    basePrice: 80,
    duration: "40-60 min",
    distance: "45 km",
    image: "/vehicles/stepway-paris-5.jpg",
    gallery: [
      "/vehicles/stepway-paris-5.jpg",
      "/vehicles/stepway-paris-3.jpg",
      "/vehicles/stepway-paris-4.jpg",
      "/family-transport-to-disneyland-paris-castle.jpg",
    ],
    features: [
      "Servicio puerta a puerta",
      "Conductor profesional",
      "Atención familiar",
      "Vehículos limpios y modernos",
      "Reservas confirmadas al instante",
      "Pago flexible",
      "Soporte 24/7",
      "Peajes incluidos",
    ],
    included: [
      "Seguimiento de vuelo",
      "Cartel con tu nombre",
      "Conductor de habla hispana o inglesa o francés",
      "Agua y WiFi",
      "Soporte equipaje",
      "Seguro incluido",
    ],
    amenities: [
      "WiFi a bordo",
      "Agua de cortesía",
      "Cargadores USB",
      "Climatización bizona",
      "Espacio para maletas",
      "Sillas niños (solicitar)",
    ],
    pricingOptions: [
      { label: "Hasta 4 pasajeros", price: 80 },
      { label: "5 pasajeros", price: 98 },
      { label: "6 pasajeros", price: 115 },
      { label: "7 pasajeros", price: 129 },
      { label: "8 pasajeros", price: 142 },
      { label: "Familiar XL + equipaje", price: 160 },
    ],
    pricing: {
      1: 80,
      2: 80,
      3: 80,
      4: 80,
      5: 98,
      6: 115,
      7: 129,
      8: 142,
    },
  },
  "versalles-tour": {
    title: "Tour a Versailles",
    description:
      "Explora el Palacio de Versailles y sus jardines con traslado privado y tiempo suficiente para recorrer el dominio completo.",
    basePrice: 290,
    duration: "6h promedio",
    distance: "20 km desde París",
    image: "/elegant-paris-skyline-with-eiffel-tower-and-luxury.jpg",
    gallery: [
      "/elegant-paris-skyline-with-eiffel-tower-and-luxury.jpg",
      "/vehicles/stepway-paris-6.jpg",
      "/vehicles/stepway-paris-1.jpg",
    ],
    features: [
      "Traslado ida y vuelta",
      "Tiempo libre para jardines",
      "Asistencia logística",
      "Flexibilidad de horarios",
      "Recomendaciones gastronómicas",
      "Vehículo confortable",
      "Servicio privado",
      "Opcional guía oficial",
    ],
    included: [
      "Vehículo privado",
      "Conductor bilingüe",
      "Agua a bordo",
      "Peajes y combustible",
    ],
    amenities: [
      "WiFi a bordo",
      "Cargadores USB",
      "Agua de cortesía",
      "Climatización bizona",
      "Asientos confort",
      "Espacio para compras",
    ],
    pricingOptions: [
      { label: "Hasta 3 pax base", price: 290, description: "Grupo pequeño" },
      { label: "4 pax", price: 330 },
      { label: "5 pax", price: 420 },
      { label: "6 pax", price: 510 },
      { label: "7 pax", price: 600 },
      { label: "8 pax", price: 690 },
      { label: "Añadir Guía Oficial", price: 120, description: "Requiere reserva anticipada" },
    ],
    pricing: {
      1: 290,
      2: 290,
      3: 290,
      4: 330,
      5: 420,
      6: 510,
      7: 600,
      8: 690,
    },
  },
}
